version: '3.8'

services:
  sms-spam-app:
    image: ${CI_REGISTRY_IMAGE:-sms-spam-detector}:${CI_COMMIT_SHORT_SHA:-latest}
    container_name: ${CONTAINER_NAME:-sms-spam-app}
    restart: unless-stopped
    
    # Environment variables
    environment:
      - ENVIRONMENT=production
      - APP_NAME=${APP_NAME:-sms-spam-detector}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    
    # Port mapping
    ports:
      - "${APP_PORT:-8501}:8501"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (except for specific directories)
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    
    # Volumes for persistent data
    volumes:
      - app_logs:/app/logs
      - app_models:/app/models

volumes:
  app_logs:
    driver: local
  app_models:
    driver: local

# Network configuration
networks:
  default:
    name: sms-spam-network
    driver: bridge
